from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


def get_utc_now() -> datetime:
    return datetime.now(timezone.utc)


class FlaggedLog(BaseModel):
    """Represents an individual flagged log entry from the Kafka/Rule/ML pipeline."""
    timestamp: datetime
    event_type: Literal["process", "network", "file", "auth", "dns", "alert", "other"]
    host: str
    user: Optional[str] = None
    data: Dict[str, Any] = Field(default_factory=dict)


class Incident(BaseModel):
    """Input incident payload containing context and all associated flagged logs."""
    incident_id: str
    title: str
    severity: Literal["low", "medium", "high", "critical"] = "medium"
    rule_name: str
    timestamp: datetime = Field(default_factory=get_utc_now)
    description: Optional[str] = None
    flagged_logs: List[FlaggedLog] = Field(default_factory=list)


class TimelineEvent(BaseModel):
    """Single chronological event in the attack timeline."""
    timestamp: datetime
    event_type: str
    summary: str
    details: Dict[str, Any] = Field(default_factory=dict)


class MitreItem(BaseModel):
    """MITRE ATT&CK technique mapping."""
    tactic: str
    technique_id: str
    name: str


class AffectedEntities(BaseModel):
    """Entities identified as affected or compromised in the incident."""
    hosts: List[str] = Field(default_factory=list)
    users: List[str] = Field(default_factory=list)
    suspicious_pids: List[int] = Field(default_factory=list)
    ioc_ips: List[str] = Field(default_factory=list)
    ioc_domains: List[str] = Field(default_factory=list)


class IncidentReport(BaseModel):
    """Comprehensive incident analysis generated by the multi-agent system."""
    incident_id: str
    verdict: Literal["MALICIOUS", "SUSPICIOUS", "BENIGN", "INCONCLUSIVE"]
    confidence: float = Field(ge=0.0, le=1.0)
    severity: Literal["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]
    executive_summary: str
    root_cause: str
    attack_timeline: List[TimelineEvent] = Field(default_factory=list)
    mitre_attack: List[MitreItem] = Field(default_factory=list)
    affected_entities: AffectedEntities = Field(default_factory=AffectedEntities)
    recommended_actions: List[str] = Field(default_factory=list)
    analyzed_at: datetime = Field(default_factory=get_utc_now)
